name: covid_ngs_three
channels:
  - conda-forge/label/broken
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - appdirs=1.4.3
  - async-timeout=3.0.1
  - attrs=19.3.0
  - bcftools=1.10.2
  - bcrypt=3.1.7
  - blast=2.9.0
  - boto3=1.9.191
  - botocore=1.12.191
  - bracken=1.0.0=1
  - brotlipy=0.7.0
  - bwa=0.7.17
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cachetools=3.1.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - conda=4.8.3
  - conda-package-handling=1.6.1
  - configargparse=1.2.3
  - crc32c=2.0
  - cryptography=2.9.2
  - curl=7.69.1
  - datrie=0.8.2
  - decorator=4.4.2
  - docutils=0.16
  - dropbox=9.4.0
  - entrez-direct=13.3
  - expat=2.2.9
  - fftw=3.3.8=mpi_mpich_h3f9e1be_1010
  - fgbio=1.2.0=0
  - filechunkio=1.8
  - fontconfig=2.13.1
  - freetype=2.10.2
  - ftputil=3.4
  - gdk-pixbuf=2.36.12
  - gettext=0.19.8.1
  - ghostscript=9.22
  - giflib=5.1.7
  - gitdb=4.0.5
  - gitpython=3.1.2
  - glib=2.64.2
  - gobject-introspection=1.58.2
  - google-api-core=1.17.0
  - google-auth=1.14.3
  - google-cloud-core=1.3.0
  - google-cloud-storage=1.28.1
  - google-resumable-media=0.5.0
  - googleapis-common-protos=1.51.0
  - graphite2=1.3.13
  - graphviz=2.38.0
  - gsl=2.5
  - harfbuzz=2.4.0
  - htslib=1.10.2
  - icu=67.1
  - idna=2.9
  - imagemagick=7.0.8_54
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0=0
  - ipython_genutils=0.2.0
  - java-jdk=8.0.112=1
  - jbig=2.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter_core=4.6.3
  - kmer-jellyfish=1.1.12
  - kraken=1.1.1
  - kraken2=2.0.9beta
  - krb5=1.17.1
  - ld_impl_linux-64=2.34
  - libarchive=3.3.3
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcroco=0.6.13
  - libcurl=7.69.1
  - libdeflate=1.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libiconv=1.15
  - libidn2=2.3.0
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - librsvg=2.44.14
  - libsolv=0.7.13
  - libssh2=1.8.2
  - libstdcxx-ng
  - libtiff=4.1.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - lzo=2.10
  - mamba=0.2.8
  - markupsafe=1.1.1
  - mpi=1.0=mpich
  - mpich=3.3.2
  - multidict=4.7.5
  - nbformat=5.0.6
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.18.4
  - openjdk=8.0.112=zulu8.19.0.1_3
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pango=1.40.14
  - paramiko=2.7.1
  - pcre=8.44
  - perl=5.26.2
  - perl-apache-test=1.40
  - perl-app-cpanminus=1.7044
  - perl-archive-tar=2.32
  - perl-base=2.23
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-class-load=0.25
  - perl-class-load-xs=0.10
  - perl-class-method-modifiers=2.12
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-data-optlist=0.110
  - perl-devel-globaldestruction=0.14
  - perl-devel-overloadinfo=0.005
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-dist-checkconflicts=0.11
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-eval-closure=0.14
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-getopt-long=2.50
  - perl-html-parser=3.72
  - perl-html-tagset=3.20
  - perl-html-tree=5.07
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-io-compress=2.087
  - perl-io-html=1.001
  - perl-io-socket-ssl=2.066
  - perl-io-zlib=1.10
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-libwww-perl=6.39
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-mime-base64=3.15
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-module-runtime-conflicts=0.003
  - perl-moo=2.003004
  - perl-moose=2.2011
  - perl-mozilla-ca=20180117
  - perl-mro-compat=0.13
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-package-deprecationmanager=0.17
  - perl-package-stash=0.38
  - perl-package-stash-xs=0.28
  - perl-parallel-forkmanager=2.02
  - perl-params-util=1.07
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-role-tiny=2.000008
  - perl-scalar-list-utils=1.52
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-sub-exporter=0.987
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.14
  - perl-sub-install=0.928
  - perl-sub-name=0.21
  - perl-sub-quote=2.006003
  - perl-test-requiresinternet=0.05
  - perl-time-local=1.28
  - perl-try-tiny=0.30
  - perl-types-serialiser=1.0
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44_01
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-xsloader=0.24
  - pip=20.1
  - pixman=0.38.0
  - pkg-config=0.29.2
  - popt=1.16
  - prettytable=0.7.2
  - protobuf=3.11.4
  - psutil=5.7.0
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycosat=0.6.3
  - pycparser=2.20
  - pyfasta=0.5.2
  - pygments=2.6.1
  - pygraphviz=1.5
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyrsistent=0.16.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python-irodsclient=0.8.2
  - python_abi=3.8=1_cp38
  - pytz=2020.1
  - pyyaml=5.3.1
  - ratelimiter=1.2.0
  - rclone=1.51.0
  - readline=8.0
  - requests=2.23.0
  - rsa=4.0
  - rsync=3.1.3
  - ruamel_yaml=0.15.87
  - s3transfer=0.2.1
  - samtools=1.10
  - setuptools=46.3.0
  - six=1.14.0
  - smmap=3.0.4
  - snakemake=5.17.0=0
  - snakemake-minimal=5.17.0
  - sqlite=3.31.1
  - sysroot_linux-64=2.12
  - tar
  - tk=8.6.10
  - toposort=1.5
  - tqdm=4.46.0
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wget=1.20.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.1.7
  - yarl=1.4.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pysam==0.15.4

