#!/bin/bash

FQ1=$1
FQ2=$2
OUT_FQ1=$3
OUT_FQ2=$4
TRIMMOMATIC_PATH=$5
NEXTERA_ADAPTER_PATH=$6
LOG=$7
echo $NEXTERA_ADAPTER_PATH
java -jar $TRIMMOMATIC_PATH PE $FQ1 $FQ2 $OUT_FQ1 out_r1.gz $OUT_FQ2 out_r2.gz ILLUMINACLIP:$NEXTERA_ADAPTER_PATH:2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36 2> $LOG



